In [48]:
#array in numpy
import numpy as np
a=np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0],a[1],a[2])
a[0]=5
print(a)

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [49]:
 #2d array in numpy or a matrix 2X3 matrix
b = np.array([[1,2,3],[4,5,6]])    
print(b)
print(b.shape)                     
print(b[0, 0], b[0, 1], b[1, 0])

[[1 2 3]
 [4 5 6]]
(2, 3)
1 2 4


In [50]:
# Create an array of all zeros
a = np.zeros((2,2))   
print(a)  
# Create a constant array
c = np.full((2,2), 7)  
print(c)               
 # Create a 2x2 identity matrix
d = np.eye(2)        
print(d)           
# Create an array filled with random values
e = np.random.random((2,2))  
print(e)             

[[0. 0.]
 [0. 0.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.83718942 0.32671529]
 [0.57264452 0.38839557]]


In [51]:
#indexing numpy array
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [52]:
#indexing 2d array
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)

print('2nd element on 1st row: ', arr[0, 1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd element on 1st row:  2


In [53]:
#negative indexing
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)

print('Last element from 2nd dimension: ', arr[1, -1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Last element from 2nd dimension:  10


In [54]:
#slicing array from 1 to 5
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print("normal array",arr)

print("Sliced array",arr[1:5])

normal array [1 2 3 4 5 6 7]
Sliced array [2 3 4 5]


In [55]:
#negative slicing
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print("normal array",arr)

print("Sliced array",arr[-3:-1])

normal array [1 2 3 4 5 6 7]
Sliced array [5 6]


In [56]:
# for range in first to fifth element with a gap of 2
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print("normal array",arr)

print("Sliced array",arr[1:5:2])


normal array [1 2 3 4 5 6 7]
Sliced array [2 4]


In [57]:
# slicing with a gap of element
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print("normal array",arr)

print("Sliced array",arr[::2])

normal array [1 2 3 4 5 6 7]
Sliced array [1 3 5 7]


In [58]:
#broadcasting of array
import numpy as np

a = np.array([1.0,2.0,3.0])
b = 2.0
c = a * b
print(c)


[2. 4. 6.]


In [65]:
#indexing of matrix
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0],arr[1])
print(arr[0][1],arr[1][0])


[[1 2 3]
 [4 5 6]] [[ 7  8  9]
 [10 11 12]]
[4 5 6] [7 8 9]


In [68]:
#slicing of matrix
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:3, 1:4])

[[2 3 4]
 [7 8 9]]


In [59]:
# broadcasting of matrix 
from numpy import array
a = array([[ 0.0,  0.0,  0.0],
           [10.0, 10.0, 10.0],
           [20.0, 20.0, 20.0],
           [30.0, 30.0, 30.0]])
b = array([1.0, 2.0, 3.0])
c = a + b
print(c)

[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [47]:
# using daigonal function in matrix
import numpy as np
arr = np.matrix([[9, 18, 25], 
                 [155 ,240, 68], 
                 [29, 82, 108]])
arr2 = np.diag(arr)
print(arr2)

[  9 240 108]


In [71]:
#numpy zeros function
import numpy as np  
a=np.zeros((6,2),dtype=int)  
a  

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [73]:
# numpy ones function
import numpy as np

array_2d = np.ones((2, 3),dtype=int)
print(array_2d)

[[1 1 1]
 [1 1 1]]


In [76]:
#numpy sqrt function
import numpy as np
  
# applying sqrt() method on integer numbers 
arr1 = np.sqrt([1, 4, 9, 16])
arr2 = np.sqrt([6, 10, 18])
  
print("square-root of an array1  : ", arr1)
print("square-root of an array2  : ", arr2)

square-root of an array1  :  [1. 2. 3. 4.]
square-root of an array2  :  [2.44948974 3.16227766 4.24264069]


In [79]:
#applying log function
import numpy as np
arr1 = np.array([1,2,3,4])
print (np.log(arr1))

[0.         0.69314718 1.09861229 1.38629436]


In [81]:
# appling exp function
import numpy as np
arr1 = np.array([1,2,3,4])
print(np.exp(arr1))

[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [82]:
# dot product of matrix
import numpy as np  
a = np.array([[100,200],[23,12]])  
b = np.array([[10,20],[12,21]])  
dot = np.dot(a,b)  
print(dot)  

[[3400 6200]
 [ 374  712]]


In [83]:
#matrix multiplication
import numpy as np  
a = np.array([[1,2,3],[4,5,6],[7,8,9]])  
b = np.array([[23,23,12],[2,1,2],[7,8,9]])  
mul = np.matmul(a,b)  
print(mul)  

[[ 48  49  43]
 [144 145 112]
 [240 241 181]]


In [85]:
#determinant of matrix
import numpy as np  
a = np.array([[1,2],[3,4]])  
print(np.linalg.det(a))  

-2.0000000000000004


In [87]:
#inverse of matrix
import numpy as np  
a = np.array([[1,2],[3,4]])  
print("Original matrix:\n",a)  
b = np.linalg.inv(a)  
print("Inverse:\n",b)  

Original matrix:
 [[1 2]
 [3 4]]
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [95]:
#matrix addition
import numpy as np
 
arr1 = np.array([[2, -7, 5], [-6, 2, 0]])
arr2 = np.array([[5, 8, -5], [3, 6, 9]])
print(arr1,"\n")
print(arr2,"\n")
print("sum of matrix is \n",np.add(arr1,arr2))
  

[[ 2 -7  5]
 [-6  2  0]] 

[[ 5  8 -5]
 [ 3  6  9]] 

sum of matrix is [[ 7  1  0]
 [-3  8  9]]
